Lesson 02
sanyco86/tn_shop pull request #2
Opened 2018-07-16 13:38 UTC by sanyco86

2018-07-17 12:37 UTC, VladFiliucov requested changes

2018-07-17 12:37 UTC, VladFiliucov commented on src/components/Catalog.js
> +    const products = this.props.products
Тут можно использовать дестракчеринг. Это сократит запись, да и привыкнуть к синтаксису можно ES6 быстрее.

2018-07-17 12:37 UTC, VladFiliucov commented on src/components/Catalog.js
> +    return <div>{template}</div>
Кстати, с реакт 16 уже умеет возвращать массивы из рендера. Это позволяет избежать создания кучи ненужных дивов, которые оборачивали несколько компонентов. Не говорю, что здесь это нужно. Просто полезно знать.

2018-07-17 12:37 UTC, VladFiliucov commented on src/components/Catalog.js
> +}
Скажи, а как ты выбираешь обычно писать ли класс, или функцию компонент? Например, я использую классы, только когда работаю с методами жизненного цикла, или с состоянием. Во всех остальных случаях - пишу просто функции

2018-07-17 12:37 UTC, VladFiliucov commented on src/components/product/Image.js
> +export default class Image extends Component {
Не критично, но на самом деле класс Image используется в браузере. В краайне редком случае, это может помешать работу каким-то плагинам, или расширениям. Можешь написать в браузере new Image

2018-07-17 12:37 UTC, VladFiliucov commented on src/components/product/ProductCard.js
> +        <p><Title title={data.title} /></p>
Зачем оборачивать компонент Title в параграф? По идее Title должен быть чем-то типа хэдинга, и тогда у нас выходит, что тэг p будет родительским компонентом для h1, что не правильно

2018-07-17 12:37 UTC, VladFiliucov commented on src/components/product/ProductCard.js
> +    const data = this.props.data;
можно дистракчеринг использовать

2018-07-17 12:37 UTC, VladFiliucov commented on src/components/product/ProductCard.js
> +        <p><Price price={data.price} />$</p>
unit измерения тоже должен заехать в компонент Price. Можно сделать для юнитов дефолт аргумент. Можно посмотреть в сторону новой штуки ES6, которая поддерживается всеми браузерами
http://es6-features.org/#CurrencyFormatting

2018-07-17 15:33 UTC, sanyco86 commented on src/components/product/ProductCard.js
> +        <p><Price price={data.price} />$</p>
на данном этапе считаю, что это перебор, но ссылку записал и буду изучать

2018-07-19 07:14 UTC, index01d approved these changes

2018-07-19 07:14 UTC, index01d commented on src/components/Catalog.js
> +      return <ProductCard key={product.id} data={product}/>
здесь чтобы избежать пересечений можно сделать ключ `productCard-${product.id}`

2018-07-19 08:10 UTC, merged