Lesson-03
sanyco86/tn_shop pull request #3
Opened 2018-07-25 10:15 UTC by sanyco86

2018-07-26 08:26 UTC, index01d requested changes

2018-07-26 08:26 UTC, index01d commented on src/App.js
> +        <div style={products_style}>
контейнерный компонент не должен содержать DOM-элементов

2018-07-26 08:26 UTC, index01d commented on src/App.js
> +    let cart_style     = {position: 'absolute', right: 15, top: 15, width: '30%'};
snakeCase -> camelCase

2018-07-26 08:26 UTC, index01d commented on src/App.js
> +        <div style={cart_style} onDragOver={(e)=>this.onDragOver(e)} onDrop={(e)=>this.handleDrop(e)} >
в контейнерном компоненте не должно быть обработки событий презентационного компонента

2018-07-26 08:26 UTC, index01d commented on src/App.js
> +      cart:             [],
ключ cart должен быть объектом (нечто типа { entries: [], ... }), ключи total* нужно перенести туда, иначе в состоянии будет намешано и про каталог и про корзину

2018-07-26 08:26 UTC, index01d commented on src/App.js
> +    setTimeout(function(){
это что, это зачем?

2018-07-26 08:26 UTC, index01d commented on src/App.js
> +    this.sumTotalItems(this.state.cart);
зачем здесь передаются аргументы?

2018-07-26 08:26 UTC, index01d commented on src/App.js
> +    let cartItem   = this.state.cart;
написано cartItem, а достается вся корзина

2018-07-26 08:26 UTC, index01d commented on src/App.js
> +  handleAddToCart(selectedProducts){
просто product?

2018-07-26 08:26 UTC, index01d commented on src/App.js
> +  checkProduct(productID){
зачем это нужно?

2018-07-26 08:26 UTC, index01d commented on src/App.js
> +    let cartItem   = this.state.cart;
можно просто
1) Склонировать список продуктов
2) Найти индекс необходимого
3) Если нашелся - сложить quantity и total
4) Если не нашелся - просто вставить продукт

2018-07-26 08:26 UTC, index01d commented on src/App.js
> +      total += cart[i].price * parseInt(cart[i].quantity);
parseInt нужно сделать в презентационном компоненте

2018-07-26 08:26 UTC, index01d commented on src/App.js
> +            total={totalAmount}
для передачи этих данных можно (и предполагается) использовать механизм контекста, который мы рассматривали в занятии

2018-07-26 08:26 UTC, index01d commented on src/components/Cart.js
> +          <div>
картинку, название и цену получается вынесли в компонент, а итог нет? можно добавить Total. Желательно не перемешивать в одном render'e простые и сложные компоненты

2018-07-26 08:26 UTC, index01d commented on src/components/Cart.js
> +          <a href="#" onClick={this.props.removeProduct.bind(this, product.id)}>удалить</a>
нужно деструктурировать removeProduct до return, читабельнее здесь будет стрелочная функция

2018-07-26 08:26 UTC, index01d commented on src/components/Counter.js
> +  feed(e){
лучше назвать метод handleChange, чем меньше нестандартных названий в коде, тем лучше

2018-07-26 08:26 UTC, index01d commented on src/components/Counter.js
> +        <input ref="feedQty" type="number" value={this.state.value} onChange={this.feed.bind(this)} />
bind нужно сделать в конструкторе, иначе он будет делать при каждом рендеринге, что неправильно

2018-07-26 08:26 UTC, index01d commented on src/components/Counter.js
> +    e.preventDefault();
лучше в начале метода

2018-07-26 08:26 UTC, index01d commented on src/components/Product.js
> +    this.state = { selectedProduct: {}, isAdded: false }
зачем здесь состояние?

2018-07-26 08:26 UTC, index01d commented on src/components/Product.js
> +          <button onClick={this.addToCart.bind(this, id, image, name, price, productQuantity)}>{!this.state.isAdded ? "В корзину" : "✔ Добавлено"}</button>
требует декомпозиции в отдельный компонент

2018-07-26 08:26 UTC, index01d commented on src/components/Product.js
> +          <button onClick={this.addToCart.bind(this, id, image, name, price, productQuantity)}>{!this.state.isAdded ? "В корзину" : "✔ Добавлено"}</button>
почему не передавать сразу объект product, стрелочна функция читабельнее

2018-07-26 08:26 UTC, index01d commented on src/components/Product.js
> +        <Counter productQuantity={productQuantity} updateQuantity={this.props.updateQuantity} resetQuantity={this.resetQuantity}/>
productQuantity следует переименовать просто в value value, updateQuantity: onChange, resetQuantity: onReset.

Если вынести кнопку добавления в корзину в компонент, то именно у нее будет состояние и компонент карточки останется чистым

2018-07-26 08:39 UTC, sanyco86 commented on src/App.js
> +  checkProduct(productID){
проверяет, есть ли уже этот продукт в корзине, если есть то в `handleAddToCart` будет происходить пересчет quantity и total

если нету то просто добавится в корзину

2018-07-26 10:38 UTC, index01d requested changes

2018-07-26 10:38 UTC, index01d commented on src/components/Products.js
> +    let productsStyle = {position: 'absolute', left: 15, top: 15, width: '70%'};
можно сделать константой и вытащить вообще из класса еще дальше наверх

2018-07-27 18:14 UTC, index01d requested changes
стало гораздо лучше и чище, давай еще подработаем

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +    setTimeout(() => {
все еще не ясно зачем через секунду quantity становится 1 :)

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +    setTimeout(() => {
выглядит так, что quantity должно быть в состоянии компонента кнопки добавления в корзину

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +    let entries = this.state.cart.entries;
нужно склонировать, чтобы не мутировать состояние

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +    let entries    = this.state.cart.entries;
нужно склонировать, чтобы не мутировать состояние

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +    let productID  = product.id;
промежуточные переменные теперь выглядят ненужными

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +    this.setState({ cart: {entries: entries} });
можно сократить до `cart: { entries }`

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +            onDragOver={(e)=>this.onDragOver(e)}
не должны передавать отсюда, нужно чтобы оставалось в презентационном компоненте

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +  onDragOver = (e) => {
здесь не нужен

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +  handleRemoveProduct = (id, e) => {
второй аргумент отсюда нужно исключить, мы не обрабатываем презентационные события в контейнерном компоненте

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +    e.preventDefault();
здесь быть не должно

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +    this.setState({ cart: {entries: entries} });
можно сократить до cart: { entries }

2018-07-27 18:14 UTC, index01d commented on src/components/Cart.js
> +  state = { cart: this.props.cartItems };
состояние здесь выглядит не нужным, мы можем напрямую взять данные из props. свойство лучше назвать просто items или products или entries

2018-07-27 18:14 UTC, index01d commented on src/components/Product.js
> +    <Counter value={props.productQuantity} onChange={props.updateQuantity}/>
выглядит как часть CartButton

2018-07-27 18:14 UTC, index01d commented on src/components/Products.js
> +      <Product
почему бы не передать просто product={product} ?

2018-07-27 18:14 UTC, index01d commented on src/components/product/CartButton.js
> +      selectedProduct: {
зачем здесь это состояние?

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +    for (let i=0; i<entries.length; i++) {
```
const totalAmount = reduce(
  this.state.cart.entries, 
  (acc, entry) => acc + (entry.quantity * entry.price)
);

const totalCount = this.state.entries.length;

this.setState({ cart: Object.assign({}, this.state.cart, { totalAmount, totalItems }) })
```

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +    for (let i=0; i<entries.length; i++) {
мой вариант, к исполнению необязательно, просто привел для разнообразия

2018-07-27 18:14 UTC, index01d commented on src/App.js
> +    for (let i=0; i<entries.length; i++) {
по хорошему это вообще должны быть методы-геттеры, тк мы не должны включать в состояние поля, которые можно посчитать. Проблемы производительности решаются мемоизацией

2018-07-29 08:41 UTC, index01d requested changes

2018-07-29 08:41 UTC, index01d commented on src/App.js
> +    this.setState({ cart: Object.assign({}, this.state.cart, { totalAmount, totalItems }) })
`{ cart: { ...this.state.cart, totalAmount, totalItems } }` было бы короче

2018-07-29 08:41 UTC, index01d commented on src/App.js
>            productsList={products}
просто products тоже было бы неплохо

2018-07-29 08:41 UTC, index01d commented on src/components/Cart.js
> +      <div className='cart' onDragOver={this.onDragOver} onDrop={this.props.onDrop}>
зачем сюда из свойств приходит onDrop? должен быть реализован тут же

2018-07-29 08:41 UTC, index01d commented on src/App.js
> +    quantity: 1
что означает свойство quantity?

2018-07-29 08:41 UTC, index01d commented on src/components/Cart.js
> +          <Button onClick={ (e) => removeProduct(product.id, e) } text='удалить' />
мы не должны передавать объект события куда-то дальше, все события презентационного компонента обрабатываются на месте. Стоит отдельно выделить компонент `CartItem` и компонент `RemoveButton`

2018-07-29 08:41 UTC, index01d commented on src/components/Cart.js
> +      <div className='cart' onDragOver={this.onDragOver} onDrop={this.props.onDrop}>
onDrop должен быть реализован здесь же в коде этого компонента

2018-07-30 12:19 UTC, index01d requested changes
Из большого "божественного" класса App нужно выделить компонент-контейнер состояние корзины и компонент-контейнер состояния каталога продуктов. Тогда мы сможем дальше эти компоненты упрощать.

2018-07-30 14:29 UTC, index01d approved these changes

2018-07-30 14:29 UTC, index01d commented on src/components/product/Info.js
> +const Info = ({product}) =>
можно сразу дестркктурировать `{ product: { title, price, image } }`

2018-07-30 14:29 UTC, index01d commented on src/components/product/Title.js
> +const Title = ({title}) => <p>{title}</p>;
лучше children, всегда когда значение свойства напрямую станет дочерним элементом дерево стоит пользовать children

2018-07-30 14:32 UTC, merged